version: "3.4"

services:
  db:
    image: mariadb:10
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: simpleschema_db
    ports:
      - 127.0.0.1:9836:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
    - 127.0.0.1:9811:80
    links:
    - db:db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: password